---
- name: Upgrade npm
  become: true
  shell: |
    npm install -g npm@latest

- name: Copy compiled files
  unarchive:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu/

- name: Start server
  become: true
  shell: |
    cd /home/ubuntu/backend/dist
    pm2 start main.js --name backend
    pm2 ls

  